#!/usr/bin/env python3

from subprocess import Popen
from nativemessaging import get_message


def open_in_emacs(url):
    interpreter = "/usr/bin/emacsclient -nc --eval"
    # The URL we receive should be the one we have to open. Finding that is handled by JS. So if we want to open code, it should be in pure emacs
    command = f"{interpreter} '(browse-url-emacs \"{url}\")'" if "raw" in url else f"{interpreter} '(w3m-browse-url \"{url}\")'"
    Popen(command, shell=True)


def main():
    url = get_message()["target"]
    open_in_emacs(url)


main()
